# Generated by Django 5.2.9 on 2025-12-27 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_chat",
                to="social.group",
                verbose_name="Groupe",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_group_chat",
            field=models.BooleanField(default=False, verbose_name="Chat de groupe"),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="social.group",
                verbose_name="Groupe lié",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like sur un post"),
                    ("comment", "Commentaire sur un post"),
                    ("message", "Nouveau message"),
                    ("post", "Nouveau post"),
                    ("group", "Nouveau groupe"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
