# Generated by Django 5.2.9 on 2025-12-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_conversation_group_conversation_is_group_chat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="event",
            name="organizer",
        ),
        migrations.RemoveField(
            model_name="group",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sender",
        ),
        migrations.AddField(
            model_name="conversation",
            name="participants_schools",
            field=models.ManyToManyField(
                blank=True,
                related_name="conversations",
                to="social.school",
                verbose_name="Participants écoles",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="participants_students",
            field=models.ManyToManyField(
                blank=True,
                related_name="conversations",
                to="social.student",
                verbose_name="Participants étudiants",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to="social.school",
                verbose_name="Organisateur école",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to="social.student",
                verbose_name="Organisateur étudiant",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="creator_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_groups",
                to="social.school",
                verbose_name="Créateur école",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="creator_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_groups",
                to="social.student",
                verbose_name="Créateur étudiant",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="social.school",
                verbose_name="Expéditeur école",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="social.student",
                verbose_name="Expéditeur étudiant",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="social.school",
                verbose_name="Destinataire école",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="social.student",
                verbose_name="Destinataire étudiant",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="social.event",
                verbose_name="Événement lié",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="sender_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to="social.school",
                verbose_name="Expéditeur école",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="sender_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to="social.student",
                verbose_name="Expéditeur étudiant",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like sur un post"),
                    ("comment", "Commentaire sur un post"),
                    ("message", "Nouveau message"),
                    ("post", "Nouveau post"),
                    ("group", "Nouveau groupe"),
                    ("event", "Nouvel événement"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
